networks:
  app:
    driver: bridge

services:

  db-postgres:
    image: postgres:16.1-alpine
    container_name: db_aop
    environment:
      POSTGRES_DB: aop_db
      POSTGRES_USER: aop
      POSTGRES_PASSWORD: aop
    ports:
      - "5433:5432"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Task_service
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker_1:9092
      - DYNAMIC_CONFIG_ENABLED=true

    depends_on:
      - broker_1

    networks:
      - app


  broker_1:
    image: docker.io/bitnami/kafka:3.9
    container_name:  broker_1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@broker_1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - volume1:/bitnami/kafka
    networks:
      - app

volumes:
  volume1:



